version: '3.8'

services:
  postgres:
    image: bitnami/postgresql
    container_name: fast-feet-pg
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=fast-feet
  
  cache:
    container_name: fast-feet-cache
    image: bitnami/redis
    ports:
      - 6379:6379
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    
  