version: '3.8'

services:
  postgres:
    image: bitnami/postgresql
    container_name: fast-feet-pg
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=fast-feet